name: myshedule
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  date_time_picker: ^2.0.0
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  flutterfire: ^0.0.1
  crypto: ^3.0.0
  firebase_database: ^10.0.14
  shared_preferences: ^2.0.8
  flutter_local_notifications: ^8.2.0
  firebase_messaging: ^14.0.1
  unorm_dart: ^0.2.0
  provider: ^6.0.0
  flutter_sticky_header: ^0.6.5
  flutter_localizations:
    sdk: flutter


 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
